#ifndef BARLEY_EARLY_VISUAL_TRACE_H_
#define BARLEY_EARLY_VISUAL_TRACE_H_

#include <Uefi.h>

#define BARLEY_TRACE_STAGE_FD_RESET_VECTOR       0x04U
#define BARLEY_TRACE_STAGE_SEC_MODULE_ENTRY      0x05U
#define BARLEY_TRACE_STAGE_PLATFORM_SEC_ENTRY    0x06U
#define BARLEY_TRACE_STAGE_BEFORE_MEMORY_MAP     0x07U
#define BARLEY_TRACE_STAGE_AFTER_MEMORY_MAP      0x08U
#define BARLEY_TRACE_STAGE_BEFORE_DXE_HANDOFF    0x09U
#define BARLEY_TRACE_STAGE_DXE_CORE_REACHED      0x0AU

#define BARLEY_TRACE_PLATFORM_SEC_A              0x0000FFFFU
#define BARLEY_TRACE_PLATFORM_SEC_B              0x0000FFFFU
#define BARLEY_TRACE_BEFORE_MEMORY_MAP_A          0x00FFFFFFU
#define BARLEY_TRACE_BEFORE_MEMORY_MAP_B          0x00000000U
#define BARLEY_TRACE_AFTER_MEMORY_MAP_A           0x00FF8000U
#define BARLEY_TRACE_AFTER_MEMORY_MAP_B           0x00000080U
#define BARLEY_TRACE_BEFORE_DXE_HANDOFF_A         0x0000FFFFU
#define BARLEY_TRACE_BEFORE_DXE_HANDOFF_B         0x00FF0000U
#define BARLEY_TRACE_DXE_CORE_REACHED_A           0x00FFFFFFU
#define BARLEY_TRACE_DXE_CORE_REACHED_B           0x00FF00FFU

VOID
EFIAPI
BarleyEarlyVisualTrace (
  IN UINT32 Stage,
  IN UINT32 PatternA,
  IN UINT32 PatternB
  );

#endif
