#ifndef BARLEY_EARLY_VISUAL_TRACE_H_
#define BARLEY_EARLY_VISUAL_TRACE_H_

#include <Uefi.h>

#define BARLEY_TRACE_STAGE_FD_RESET_VECTOR       5U
#define BARLEY_TRACE_STAGE_SEC_MODULE_ENTRY      6U
#define BARLEY_TRACE_STAGE_AFTER_PLATFORM_INIT   7U
#define BARLEY_TRACE_STAGE_SEC_C_ENTRY           8U
#define BARLEY_TRACE_STAGE_MEMORY_MAP_CREATED    9U
#define BARLEY_TRACE_STAGE_BEFORE_DXE_HANDOFF   10U
#define BARLEY_TRACE_STAGE_DXE_CORE_REACHED     11U
#define BARLEY_TRACE_STAGE_GOP_ENTRY            12U
#define BARLEY_TRACE_STAGE_CONOUT_USABLE        13U
#define BARLEY_TRACE_STAGE_BEFORE_SHELL         14U
#define BARLEY_TRACE_STAGE_SHELL_ENTRY          15U

VOID
EFIAPI
BarleyEarlyVisualTrace (
  IN UINT32 Stage,
  IN UINT32 PatternA,
  IN UINT32 PatternB
  );

#endif
